return {
  -- you can pin a tool to a particular version
  -- { 'golangci-lint', version = 'v1.47.0' },
  -- you can turn off/on auto_update per tool
  -- { 'bash-language-server', auto_update = true },
  ---------- LSP ----------
  "awk-language-server",
  "bash-language-server",
  -- "buf-language-server",
  -- "clangd",
  -- "cmake-language-server",
  "css-lsp",
  "cssmodules-language-server",
  "diagnostic-languageserver",
  "dockerfile-language-server",
  -- "dot-language-server",
  -- "eslint-lsp",
  "golangci-lint-langserver",
  "gopls",
  "html-lsp",
  "json-lsp",
  "marksman",
  "python-lsp-server",
  "pyright",
  -- "remark-language-server", -- A language server to lint and format markdown files with remark.
  -- "rust-analyzer",
  "sqls",
  "lua-language-server",
  -- "taplo",
  "terraform-ls",
  "typescript-language-server",
  "vim-language-server",
  -- "vue-language-server",
  "yaml-language-server",

  ---------- DAP ----------
  -- "chrome-debug-adapter",
  -- "mockdebug",
  -- "cpptools",
  -- "bash-debug-adapter",
  -- "delve",
  -- "go-debug-adapter",
  ---------- Linter ----------
  -- "cspell",
  -- "textlint",
  -- "sqlfluff",
  -- "vulture",
  -- "cmakelang",
  "codespell",
  "editorconfig-checker",
  -- "eslint_d",
  "flake8",
  "gitlint",
  "golangci-lint",
  "luacheck",
  "markdownlint",
  "pylint",
  -- "revive",
  "shellcheck",
  "shellharden",
  "yamllint",
  ---------- Formatter ----------
  -- "buf",
  "luaformatter",
  "prettierd",
  "fixjson",
  -- "prettier",
  "golines",
  "autopep8",
  -- "clang-format",
  -- "cmakelang",
  "gofumpt",
  "goimports",
  "jq",
  "markdownlint",
  "shellharden",
  "shfmt",
  "sql-formatter",
  "stylua",
}
