return {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        -- you can pin a tool to a particular version
        -- { 'golangci-lint', version = 'v1.47.0' },
        -- you can turn off/on auto_update per tool
        -- { 'bash-language-server', auto_update = true },
        ---------- LSP ----------
        "ansible-language-server",
        "ansible-lint",
        "autoflake",
        "autopep8",
        "awk-language-server",
        "bash-language-server",
        "black",
        "codespell",
        "commitlint",
        "diagnostic-languageserver",
        "dockerfile-language-server",
        "editorconfig-checker",
        "fixjson",
        "flake8",
        "gitlint",
        "gofumpt",
        "goimports",
        "goimports-reviser",
        "golangci-lint",
        "golangci-lint-langserver",
        "golines",
        "gopls",
        "hadolint",
        "isort",
        "jq",
        "json-lsp",
        "jsonlint",
        "lua-language-server",
        "luacheck",
        "luaformatter",
        "markdownlint",
        "markdownlint",
        "marksman",
        "prettier",
        "prettierd",
        "pylint",
        "pyproject-flake8",
        "pyright",
        "python-lsp-server",
        "ruff",
        "ruff-lsp",
        "shellcheck",
        "shellharden",
        "shellharden",
        "shfmt",
        "sql-formatter",
        "sqlls",
        "stylua",
        "terraform-ls",
        "tflint",
        "typescript-language-server",
        "vim-language-server",
        "yaml-language-server",
        "yamlfmt",
        "yamllint",
        "yapf",
      },
    },
  },
}
